# Generated by Django 5.1.7 on 2025-08-10 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('detail', models.TextField()),
                ('color', models.CharField(max_length=20)),
                ('background', models.CharField(max_length=20)),
                ('text_color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LabExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('goal', models.JSONField(default=list)),
                ('contents', models.JSONField(default=list)),
                ('system', models.JSONField(default=list)),
                ('lab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='core.lab')),
            ],
        ),
        migrations.CreateModel(
            name='LabImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='labs/')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.lab')),
            ],
        ),
    ]
